name: v2-clash

# 触发条件 (Условия триггера)
on:
  workflow_dispatch:
  schedule:
    # 表达式生成  https://crontab.guru/
    # Запуск каждые 3 часа в 05 минут
    - cron: '05 */3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Даём права на запись изменений обратно в репозиторий
      
    steps:
    - name: 迁出代码 (Checkout code)
      uses: actions/checkout@v4

    - name: 安装Python (Setup Python)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 加载缓存 (Load cache)
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 设置时区 (Set Timezone)
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 安装依赖 (Install dependencies)
      run: |
        pip install -r ./requirements.txt

    - name: 执行任务 (Execute script)
      run: |
        python ./Test.py

    - name: 提交更改 (Commit changes)
      id: commit_check
      run: |                  
        # Защита от пустых секретов: если секрет пустой, включится стандартный бот
        git config --local user.email "${{ secrets.EMAIL || 'github-actions[bot]@users.noreply.github.com' }}"
        git config --local user.name "${{ secrets.NAME || 'github-actions[bot]' }}"
        
        # Твоя родная проверка файла output.yaml
        if git status --porcelain | grep -q "output.yaml"; then
          git add ./output.yaml
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') v2_clash_update"
          
          # Делаем pull строго ПОСЛЕ коммита
          git pull origin main --rebase
          
          echo "HAS_CHANGES=true" >> $GITHUB_ENV
        else
          echo "Изменений в output.yaml нет. Пропускаем шаг пуша."
          echo "HAS_CHANGES=false" >> $GITHUB_ENV
        fi

    - name: 推送更改 (Push changes)
      if: env.HAS_CHANGES == 'true'
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
